/* eslint-disable */

// import Test from '@/components/Test';
import {
    Box,
    Button,
    Center,
    Container,
    HStack,
    Input,
    SimpleGrid, Text
} from '@chakra-ui/react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useState } from 'react';
import { DragDropContext } from 'react-beautiful-dnd';
/* eslint-enable */

const Test = dynamic(() => import('@/components/ColumnComponent'), { ssr: false });
const tasks = [
    { id: 1, label: 'Task 01' },
    { id: 2, label: 'Task 02' },
    { id: 3, label: 'Task 03' },
];
const columns = {
    'column-1': {
        name: 'To do',
        items: tasks,
    },
    'column-2': {
        name: 'In Progress',
        items: [],
    },
    'column-3': {
        name: 'Done',
        items: [],
    },
};

const initialData = {
    tasks: {
        1: { id: 1, content: 'Configure Next.js application' },
        2: { id: 2, content: 'Configure Next.js and tailwind ' },
        3: { id: 3, content: 'Create sidebar navigation menu' },
        4: { id: 4, content: 'Create page footer' },
        5: { id: 5, content: 'Create page navigation menu' },
        6: { id: 6, content: 'Create page layout' },
    },
    columns: {
        'column-1': {
            id: 'column-1',
            title: 'TO-DO',
            taskIds: [1, 2, 3, 4, 5, 6],
        },
        'column-2': {
            id: 'column-2',
            title: 'IN-PROGRESS',
            taskIds: [],
        },
        'column-3': {
            id: 'column-3',
            title: 'COMPLETED',
            taskIds: [],
        },
    },
    // Facilitate reordering of the columns
    columnOrder: ['column-1', 'column-2', 'column-3'],
};

export default function Home() {
    const [status, setStatus] = useState(initialData);
    console.log('🚀 ~ status', status);

    const onDragEnd = (result) => true;

    return (
        <>
            <Head>
                <title>Kanban Board</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container maxW="7xl" p="4" overflow="hidden">
                <Center h="40px" color="white">
                    <HStack spacing="4">
                        <Input
                            placeholder="Write your task ..."
                            borderRadius="none"
                            border="1px solid black"
                        />
                        <Button borderRadius="none" px="8" border="1px solid black" bg="white">
                            <Text color="red.500" fontWeight="semibold">
                                Add
                            </Text>
                        </Button>
                    </HStack>
                </Center>

                <DragDropContext onDragEnd={onDragEnd}>
                    <Box pt="6">
                        <SimpleGrid columns="3" spacing={10}>
                            {status.columnOrder.map((columnId) => {
                                console.log('🚀 ~ columnId', columnId);
                                const column = status.columns[columnId];
                                const tasks = column.taskIds.map(
                                    // eslint-disable-next-line comma-dangle
                                    (taskId) => status.tasks[taskId]
                                );
                                return (
                                    <Box
                                        border="1px solid black"
                                        key={columnId}
                                        minH="500"
                                        maxH="500"
                                        overflow="auto"
                                    >
                                        <Text
                                            bg="tomato"
                                            fontSize="2xl"
                                            fontWeight="bold"
                                            align="center"
                                            p="2"
                                        >
                                            {column?.title}
                                        </Text>
                                        <Test column={column} tasks={tasks}></Test>
                                    </Box>
                                );
                            })}
                        </SimpleGrid>
                    </Box>
                </DragDropContext>
            </Container>
        </>
    );
}
