/* eslint-disable */
import {
  Box,
  Button,
  Center,
  Container,
  HStack,
  Input,
  SimpleGrid, Text,
  VStack
} from '@chakra-ui/react';
import Head from 'next/head';
/* eslint-enable */

export default function Home() {
    return (
        <>
            <Head>
                <title>Kanban Board</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container maxW="7xl" p="4">
                <Center h="40px" color="white">
                    <HStack spacing="4">
                        <Input
                            placeholder="Write your task ..."
                            borderRadius="none"
                            border="1px solid black"
                        />
                        <Button borderRadius="none" px="8" border="1px solid black" bg="white">
                            <Text color="red.500" fontWeight="semibold">
                                Add
                            </Text>
                        </Button>
                    </HStack>
                </Center>

                <Box pt="6">
                    <SimpleGrid columns="3" spacing={10}>
                        <Box border="1px solid black">
                            <Text bg="tomato" fontSize="2xl" fontWeight="bold" align="center" p="2">
                                To Do
                            </Text>

                            <VStack spacing="4" align="stretch" p="4">
                                <Text
                                    bg="blackAlpha.200"
                                    color="blackAlpha.600"
                                    fontSize="lg"
                                    fontWeight="semibold"
                                    align="center"
                                    p="2"
                                    border="1px solid black"
                                >
                                    Task 01
                                </Text>
                                <Text
                                    bg="blackAlpha.200"
                                    color="blackAlpha.600"
                                    fontSize="lg"
                                    fontWeight="semibold"
                                    align="center"
                                    p="2"
                                    border="1px solid black"
                                >
                                    Task 01
                                </Text>
                                <Text
                                    bg="blackAlpha.200"
                                    color="blackAlpha.600"
                                    fontSize="lg"
                                    fontWeight="semibold"
                                    align="center"
                                    p="2"
                                    border="1px solid black"
                                >
                                    Task 01
                                </Text>
                            </VStack>
                        </Box>
                    </SimpleGrid>
                </Box>
            </Container>
        </>
    );
}
