/* eslint-disable max-len */
/* eslint-disable */
import {
  Box,
  Button,
  Center,
  Container,
  HStack,
  Input,
  SimpleGrid, Text, VStack
} from '@chakra-ui/react';
import Head from 'next/head';
import { useState } from 'react';
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd';
import { v4 as uuidv4 } from 'uuid';
/* eslint-enable */

export default function Home() {
    const tasks = [
        { id: uuidv4(), label: 'Task 01' },
        { id: uuidv4(), label: 'Task 02' },
        { id: uuidv4(), label: 'Task 03' },
    ];
    const columns = {
        [uuidv4()]: {
            name: 'To do',
            items: tasks,
        },
        [uuidv4()]: {
            name: 'In Progress',
            items: [],
        },
        [uuidv4()]: {
            name: 'Done',
            items: [],
        },
    };

    const [status, setStatus] = useState(columns);

    return (
        <>
            <Head>
                <title>Kanban Board</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container maxW="7xl" p="4">
                <Center h="40px" color="white">
                    <HStack spacing="4">
                        <Input
                            placeholder="Write your task ..."
                            borderRadius="none"
                            border="1px solid black"
                        />
                        <Button borderRadius="none" px="8" border="1px solid black" bg="white">
                            <Text color="red.500" fontWeight="semibold">
                                Add
                            </Text>
                        </Button>
                    </HStack>
                </Center>

                <Box pt="6">
                    <SimpleGrid columns="3" spacing={10}>
                        <DragDropContext onDragEnd={(result) => console.log(result)}>
                            {Object?.entries(status)?.map(([columnId, column], index) => {
                                console.log('🚀 ~ columnId', column);
                                return (
                                    <Box border="1px solid black" key={columnId}>
                                        <Text
                                            bg="tomato"
                                            fontSize="2xl"
                                            fontWeight="bold"
                                            align="center"
                                            p="2"
                                        >
                                            {column?.name}
                                        </Text>
                                        <Droppable droppableId={columnId}>
                                            {(dropProvided, dropSnapshot) => (
                                                <Box
                                                    {...dropProvided.droppableProps}
                                                    ref={dropProvided.innerRef}
                                                >
                                                    <VStack spacing="4" align="stretch" p="4">
                                                        {column?.items?.map((item, index) => (
                                                            <Draggable
                                                                draggableId={item.id}
                                                                key={item.id}
                                                                index={index}
                                                            >
                                                                {(dragProvided, dragSnapshot) => (
                                                                    <Text
                                                                        bg="blackAlpha.200"
                                                                        color="blackAlpha.600"
                                                                        fontSize="lg"
                                                                        fontWeight="semibold"
                                                                        align="center"
                                                                        p="2"
                                                                        border="1px solid black"
                                                                        key={item.id}
                                                                        ref={dragProvided.innerRef}
                                                                        {...dragProvided.draggableProps}
                                                                        {...dragProvided.dragHandleProps}
                                                                    >
                                                                        {item.label}
                                                                    </Text>
                                                                )}
                                                            </Draggable>
                                                        ))}
                                                        {dropProvided.placeholder}
                                                    </VStack>
                                                </Box>
                                            )}
                                        </Droppable>
                                    </Box>
                                );
                            })}
                        </DragDropContext>
                    </SimpleGrid>
                </Box>
            </Container>
        </>
    );
}
